project_id: "518190"
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: true

files:
  - source: /lang/en-US.ftl
    translation: /lang/%locale%.ftl
    update_option: update_as_unapproved
